site_name: Monica Mohan
site_description: Project updates
site_author: Monica Mohan
site_url: https://github.com/gisbymonica


# Copyright
copyright: 'Copyright &copy; 2021 - 2022 Monica Mohan'


# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Google Sans Serif
    code: Regular
  favicon: assets/favicon.png
  icon:
    logo: logo

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gisbymonica
    - icon: fontawesome/brands/medium
      link: https://medium.com/@monicamohangis
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samapriya

# Page tree
nav:
  - About me: aboutme.md
