site_name: Monica Mohan
site_description: GitHub Projects and CV
site_author: Monica Mohan
site_url: https://github.com/gisbymonica
docs_dir: docs/


# Copyright
copyright: 'Copyright &copy; 2021 - 2022 Monica Mohan'


# Configuration
theme:
  name: 'material'


# Page tree
nav:
  - About me: aboutme.md
